import "./globals.css";

export const metadata = {
  title: "Products",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.boxicons.com/fonts/basic/boxicons.min.css"
          rel="stylesheet"
        />
        <link
          href="https://cdn.boxicons.com/fonts/brands/boxicons-brands.min.css"
          rel="stylesheet"
        />
      </head>
      <body className="font-sans md:p-6 p-0 ">
      
        {children}
      </body>
    </html>
  );
}
